* Description

This is the github repository of the *mod project* folder for my [[https://steamcommunity.com/sharedfiles/filedetails/?id=2823002635][Playable Rulers mod]]. 
This will be the most up to date project folder from the mod, even before it's on steam.

* How to build the mod

** What you will need

- The Modbuddy SDK (Search in the steam's tool sections)
- Follow the wondeful [[https://www.reddit.com/r/xcom2mods/wiki/firsttime#wiki_how_to_install_and_set_up_xcom_2_wotc_sdk][guide from the Xcom 2 modding subreddit]]
- Start the SDK, go in file then "open mod project" (you will need to extract the project's folder).
- Then do your changes (DO NOT CHANGES the =XcomEditor.ini=, =XcomEngine.ini= and =XcomGame.ini= or the mod will throw in an errors. In general, don't change the content in the =.uc= file unless you know what you are doing)

** Mod used by the mod

*** Required mod

Required mod = [[https://steamcommunity.com/sharedfiles/filedetails/?id=1561030099][Mitzruti's Perk Pack]], [[https://steamcommunity.com/workshop/filedetails/?id=1134256495][X2WOTCCommunityHighlander]], [[https://steamcommunity.com/sharedfiles/filedetails/?id=1124713229][Custom Soldier Evac Fix]] and [[https://steamcommunity.com/sharedfiles/filedetails/?id=2534737016][Alien Hunters Community Highlander]]

(The perk pack is not *required*, but a lot of ability won't work or will need new ability tree.)

*** Optional mod

Optional mod = [[https://steamcommunity.com/sharedfiles/filedetails/?id=2819129273][UFOpedia & Bestiary]] (this mod add entry for the captured rulers. They are made by Endlesspie49).

* FAQ

** Why not post the "ready to use" version of the mod ?

Because it allows you to change the source code and compile the mod as you see fit. If enough people ask, I will release the proper mod to github as well.

** Can I do mod requests and bug reports ?

*YES*, you can. You can even make pull request if you know what you are doing.

** Can I fork it ?

Yes you can, just credit the original author (Gazgemauch) and me.